config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    resources :items, only: [:index, :show]
    
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
  
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirm'
        post 'confirm'
        get 'complete'
      end
    end
  
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    root to: "homes#top"
    get 'home/about' => 'homes#about' , as: "about"
  end
  
  namespace :public do
    get '/customers/profile' => 'customers#show'
    get '/customers/profile/edit' => 'customers#edit'
    patch '/customers/profile' => 'customers#update'
    get  '/customers/profile/check' => 'customers#check'
    patch  '/customers/profile/withdraw' => 'customers#withdraw'
  end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum select_address: { current_customer_address: 0, addresses: 1, new_address: 2 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    
    @order.update(order_params)
      if @order.status == "payment_confirmation"
        @order_details.update_all(crafting_status: 1) 
    ## ①注文ステータスが「入金確認」のとき、製作ステータスを全て「製作待ち」に更新する
      end
    flash[:notice] = 'ステータスを更新しました'
    redirect_to admin_order_path(@order)
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all
    @order_detail = OrderDetail.find(params[:id])
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h3><strong>注文履歴詳細</strong></h3>
  <div class="row">
    <div class="col-12">
      <table class="table table-borderless">
        <tr>
          <td style="width: 20%"><strong>購入者</strong></td>
          <td><%= @order.customer.full_name %></td>
        </tr>
        <tr>
          <td><strong>注文日</strong></td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td><strong>配送先</strong></td>
          <td>〒<%= @order.postal_code %> <%= @order.address %><br> <%= @order.name %></td>
        </tr>
        <tr>
          <td><strong>支払い方法</strong></td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td><strong>注文ステータス</strong></td>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f|  %>
              <%= f.select :status, options_for_select(Order.statuses.map { |k, v| [I18n.t("enums.order.status.#{k}"), k] }, @order.status), class: "status" %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <table class="table table-inverse">
        <thead class="table-secondary">
          <tr>
            <th style="width: 25%">商品名</th>
            <th style="width: 20%">単価(税込)</th>
            <th style="width: 12%">数量</th>
            <th style="width: 13%">小計</th>
            <th style="width: 30%">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= order_detail.subtotal.to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f|  %>
                  <%= f.select :crafting_status, options_for_select(OrderDetail.crafting_statuses.map { |k, v| [I18n.t("enums.order_detail.crafting_status.#{k}"), k] }, order_detail.crafting_status), class: "crafting_status" %>
                  <%= f.submit "更新", class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <tr>
          <td style="width: 50%"><strong>商品合計</strong></td>
          <td><%= @order_details.sum { |order_detail| order_detail.price_including_tax * order_detail.quantity }.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td><strong>送料</strong></td>
          <td><%= @order.postage %>円</td>
        </tr>
        <tr>
          <td><strong>請求金額合計</strong></td>
          <td><%= @order.billing_amount.to_s(:delimited) %>円</td>
        </tr>
  </div>
</div>