config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    resources :items, only: [:index, :show]
    
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
  
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'confirm'
        post 'confirm'
        get 'complete'
      end
    end
  
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    root to: "homes#top"
    get 'home/about' => 'homes#about' , as: "about"
  end
  
  namespace :public do
    get '/customers/profile' => 'customers#show'
    get '/customers/profile/edit' => 'customers#edit'
    patch '/customers/profile' => 'customers#update'
    get  '/customers/profile/check' => 'customers#check'
    patch  '/customers/profile/withdraw' => 'customers#withdraw'
  end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    root to: "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  validates :item_id, :amount, :customer_id, presence: true
  validates :amount, numericality:{ only_integer: true }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name, presence: true
  validates :first_name_kana, presence: true
  validates :email, uniqueness: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
  def full_name
    last_name + ' ' + first_name
  end
  
  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end
  
  def status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  
  def with_tax_price
    (price*1.1).floor
  end
  
  def status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end
  
  # Itemモデル内のget_imageメソッドを修正
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize: "#{width}x#{height}!").processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum select_address: { current_customer_address: 0, addresses: 1, new_address: 2 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  enum crafting_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
  
  def subtotal
    item.with_tax_price * quantity
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルが追加されました"
      redirect_to admin_genres_path
    else
      flash[:notice] = "ジャンルの追加に失敗しました"
      @genres = Genre.all
      render :index
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    # @genres = Genres.all
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "更新に成功しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品が追加されました"
      redirect_to admin_item_path(@item.id)
    else
      flash[:notice] = "商品の追加に失敗しました"
      render :new
      # バリデーションエラーを確認
      puts @item.errors.full_messages
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @cart_item =CartItem
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "更新に成功しました"
      redirect_to admin_item_path(@item.id)
    else
      flash[:notice] = "更新に失敗しました"
      render admin_item_path(@item.id)
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

    # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    if resource.is_a?(Admin)
      admin_root_path
    else
      public_customers_profile_path
    end
  end

    # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="style.css" />
    <script src="https://kit.fontawesome.com/a5b17d123b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      .background-image {
      background-image: url('/assets/background.jpeg');
      background-size: cover;
      background-repeat: no-repeat;
      }
    </style>

  </head>

  <body>
    <header class="mb-3">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <%= link_to root_path, class: 'nav-link text-dark' do %>
            <span>ながのcake</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            
            <!--会員ログイン時ヘッダー-->
            
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to public_customers_profile_path, class: 'nav-link text-dark' do %>
                <span>マイページ</span>
              <% end %>
            </li>
            <!--商品一覧-->
            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link text-dark' do %>
                <span>商品一覧</span>
              <% end %>
            </li>
            <!--カート内-->
            <li class="nav-item">
              <%= link_to cart_items_path, class: 'nav-link text-dark' do %>
                <span>カート</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <span>ログアウト</span>
              <% end %>
            </li>
            
            <!--管理者ログイン時ヘッダー-->
            <% elsif admin_signed_in? %>
            <!--商品一覧-->
            <li class="nav-item">
              <%= link_to admin_items_path, class: 'nav-link text-dark' do %>
                <span>商品一覧</span>
              <% end %>
            </li>
            <!--会員一覧-->
            <li class="nav-item">
              <%= link_to admin_customers_path, class: 'nav-link text-dark' do %>
                <span>会員一覧</span>
              <% end %>
            </li>
            <!--注文履歴一覧-->
            <li class="nav-item">
              <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
                <span>注文履歴一覧</span>
              <% end %>
            </li>
            <!--ジャンル一覧-->
            <li class="nav-item">
              <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                <span>ジャンル一覧</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <span>ログアウト</span>
              <% end %>
            </li>
            <!--非ログイン時-->
            <% else %>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-dark' do %>
                <span>About</span>
              <% end %>
            </li>
            <!--商品一覧-->
            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link text-dark' do %>
                <span>商品一覧</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class: 'nav-link text-dark' do %>
                <span>新規登録</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path, class: 'nav-link text-dark' do %>
                <span>ログイン</span>
              <% end %>
            </li>
            <% end %>
            
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="max-auto">
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>